-- MySQL Script generated by MySQL Workbench
-- Wed Nov 22 15:22:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blogdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blogdb` ;

-- -----------------------------------------------------
-- Schema blogdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogdb` DEFAULT CHARACTER SET utf8 ;
USE `blogdb` ;

-- -----------------------------------------------------
-- Table `blogdb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogdb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(64) NOT NULL,
  `foto` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogdb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogdb`.`post` (
  `id` INT NOT NULL,
  `id_usuario` INT NULL,
  `titulo` VARCHAR(120) NOT NULL,
  `data` DATETIME NOT NULL,
  `texto` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_post_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `blogdb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
